### ISSUE TITLE
Seo para angular

### ISSUE THREAD

**Issue by LeonardoBevilacqua** [MarcioLMM/tcc-faculdade#19]
**Objetivo:**

Pesquisar sobre SEO utilizando angular

[Angular-6-SEO](https://coursetro.com/posts/code/155/Angular-6-SEO-Tutorial-from-Scratch---It's-Super-Simple-Now!)

**Comment by capp59marcelo** [comment]
https://medium.com/codingthesmartway-com-blog/angular-seo-making-angular-6-single-page-web-apps-search-engine-friendly-c8ec4ff2f549

**Comment by capp59marcelo** [comment]
https://blog.angular-university.io/angular-2-universal-meet-the-internet-of-the-future-seo-friendly-single-page-web-apps/
