### ISSUE TITLE
[MVP] 3jobs-api

### ISSUE THREAD

**Issue by LeonardoBevilacqua** [MarcioLMM/tcc-faculdade#5]
**Objetivos:**

- [ ] CRUD de usuários (verificar se o framework já disponibiliza de forma fácil)
- [ ] CRUD de perfil
- [ ] CRUD de vagas
- [ ] Criação do processo de armazenamento das fotos e utilização pelo backend.
- [ ] Será estruturado o arquivo Dockerfile para possibilitar a criação da imagem da aplicação.

-----

A partir do protótipo, iniciar o desenvolvimento do MVP.
O projeto será separado em duas pasta: 3jobs-web e 3jobs-api.

3jobs-api: onde se encontra o backend do sistema, para o MVP, deverá ser possível realizar o CRUD de conta, perfil e vagas. (talvez seja necessario mais algum).

**Comment by LeonardoBevilacqua** [comment]
Para que assumir esse card:
Deve já ser criado:

- [ ] CRUD de usuários (verificar se o framework já disponibiliza de forma fácil)
- [ ] CRUD de perfil
- [ ] CRUD de vagas

Deve ser trabalho em conjunto com card #6 [WEB].

**Comment by LeonardoBevilacqua** [comment]
@MarcioLMM Escrever seu progresso no card e controlar ele

**Comment by MarcioLMM** [comment]
Alem da criação do CRUD sera feito algumas tasks a mais:
- Criação do processo de armazenamento das fotos e utilização pelo backend.
- Sera estruturado o arquivo Dockerfile para possibilitar a criação da imagem da aplicação.
