### ISSUE TITLE
Analise e restruturação de conteúdo do dashboard.

### ISSUE THREAD

**Issue by thiiluh** [MarcioLMM/tcc-faculdade#52]
Analisar o conteúdo para ser incrementado no dashboard.
**Todo**
- Remover item

**dashboard ADMIN e RECRUTADOR**
- add status -> jobs.
- paginar tabela "vagas".
- "Ver perfil" redirecionar para `jobs-dashboard`.
- add botão editar, reaproveitando o modal.
- Status: 
   - Criado -> vaga aguardando headhunter (headhunters pode buscar por elas)
   - Aberto -> headhunter foi aprovado. (candidatos apenas podem buscar por elas)
   - Fechado -> fechado pelo usuário.
   - Pausado -> pausado pelo usuário.
   - Expirado -> após a data. (job)
   - Pendente -> headhunter se cadastrou e aguarda aprovação.
- "Todo list" com mesmo tamanho que "Vagas"
- Eliminar tabela headhunter -> inserir lista dentro de `job-dashboard`
- [OPCIONAL] Alterar tabela headhunters para lista de RECRUTADORES_COMUNS

**Dashboard da vaga ADMIN e RECRUTADOR**

- Uma vaga possui apenas um headhunter.
- Retirada do combo, transformado em uma pagina nova
- cards
    - qtd candidatos
   - qtd avalidados (add status no relacionamento jobs e users)
- tabela candidatos
   - avaliação de 0 a 10
   - exibir email do candidato
   - status
- gráfico de barras da cidades
- remover o gráfico candidatos

-----

**Dashboard headhunter**
- card
   - vagas participando
   - vagas pedentes
   - vagas finalizadas
 - tabela similar ao de recrutadores.

**Dashboard vaga headhunter**
- tabela de candidatos
   - exibir quem realizou questionario
   - exibir link para porrifólio (add no profile)
   - avaliar usuário
   - sem gráficos

----

**Dashboard candidato**

- Visualização simples de vagas que esta participando
- detalhes redireciona para `job-details`
- Possibilidade de desistir da vaga
- Questionários pedentes da vaga

**Comment by capp59marcelo** [comment]
**ADMIN**
![image](https://user-images.githubusercontent.com/35183237/64653457-da591000-d3fc-11e9-89fd-a4365dd91793.png)

**Comment by capp59marcelo** [comment]
- [ ] No painel de rank exibir no topo o headhunter e embaixo manter dinamica.
