### ISSUE TITLE
Busca de vagas usando endpoint

### ISSUE THREAD

**Issue by LeonardoBevilacqua** [MarcioLMM/tcc-faculdade#57]
- Depende da #56 mas pode ser feito sem ele usando postman
- Verificar se existe endpoint

- [x] Add um parâmetro para Title
- [ ] Add um parâmetro para TAG
- [x]  Não diferenciar letrar maiúscula e minusculo no paramento do filtro

**Comment by MarcioLMM** [comment]
Existe um endpoint /jobs que retorna todas as vagas, no momento está faltando a opção de paginação e possiveis filtros de pesquisa, vou adicionar esse final de semana.

**Comment by MarcioLMM** [comment]
No endpoint /jobs tbm esta disponivel o POST para criar novas vagas.

Exemplo rapido:

{
	"title": "java engineer",
	"description": "vaga de Python", 
	"users": [{
		"id": 6
	}],
	"company": {
		"id": 13
	}
}

users não é obrigatorio, company é pois toda vaga está linkada em uma empresa

**Comment by LeonardoBevilacqua** [comment]
-Busca por tags e titulo,
-Filtro por cidade, experiencia do candidato
