### ISSUE TITLE
Fixes backend

### ISSUE THREAD

**Issue by LeonardoBevilacqua** [MarcioLMM/tcc-faculdade#77]
**Objetivo**

Card responsável por listar erros de backend para serem ajustados.

**Fixes/improvements:**

- Models:
   - [x] data não conter horas.
- Geral:
   - [ ] criação de testes unitários (abrir novo card?)
   - [ ] verificar se existe a necessidade de algum endpoint especifico que ainda não criado.
   - [ ] adicionar profile de prod dentro do dockerfile

-----
- [x] Criar endpoint para trazer todos os recutadores que pertencem a compania.
- [x] Criar endpoint com total (Processos, Pendente, Atrasado, Finalizado) será usado nos card.
- [x] Criar endpoint para cadastrar esse recrutador.
- [x] Criar endpoint com quantidade (candidatos, avaliados) da vaga.
- [x] Criar endpoint que retorna as cidades dos candidatos e quantidade será usado no gráfico duvida perguntar ao marcelo
- [x] Criar endpoint que traz o headhunter e os candidatos da vaga, no headhunter é necessario vim a url da foto dele

**Comment by capp59marcelo** [comment]
- [ ] Criar endpoint para trazer todos os recutadores que pertencem a compania.
- [ ] Criar endpoint com total (Processos, Pendente, Atrasado, Finalizado) será usado nos card.
- [ ] Criar endpoint para cadastrar esse recrutador.
- [ ] Criar endpoint com quantidade (candidatos, avaliados) da vaga.
- [ ] Criar endpoint que retorna as cidades dos candidatos e quantidade será usado no gráfico duvida perguntar ao marcelo
- [ ] Criar endpoint que traz o headhunter e os candidatos da vaga, no headhunter é necessario vim a url da foto dele
